server:
  #端口
  port: 8766
  #设置post请求大小
  tomcat:
    max-http-post-size: -1

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          #启用基于服务发现的路由定位
          enabled: true
          #开启小写 默认路由是大写的
          lowerCaseServiceId: true



eureka:
  #客户端
  client:
    #注册中心地址
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    #将自己的IP注册到eureka
    prefer-ip-address: true
    #instance-id 是再注册中心页面显示的微服务名。
    instance-id: ${spring.application.name}:${server.port}

#监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
