#作为制定应用在任何profile下都通用的配置文件
spring:
  # 静态资源路径
  resources:
    static-locations: classpath:static/,file:static/
  mvc:
    static-path-pattern: /static/**
#日志
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
    org.springframework.cloud.openfeign: DEBUG

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#feign
feign:
  hystrix:
    enabled: true