jdbc_driver=com.mysql.cj.jdbc.Driver
#jdbc_url=jdbc:mysql://localhost:3306/basedemo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
jdbc_url=jdbc:mysql://localhost:3306/basedemo?serverTimezone=UTC&zeroDateTimeBehavior=round&nullCatalogMeansCurrent=true
jdbc_user=root
jdbc_password=a

#daoPackage=com.example.mybaitis.dao
modelPackage=com.linzd.pc.entity
resourcesPackage=mapper


models= src/main/java
resources=src/main/resources
dao=src/main/java