package com.linzd.mobile.entity;

import java.io.Serializable;
import java.util.Date;

import io.swagger.annotations.ApiModel;
import lombok.Data;

/**
 * Table: attachment
 */
@Data
@ApiModel(value="Attachment",description="附件Attachment")
public class Attachment implements Serializable {
    /**
     * 主键
     *
     * Table:     attachment
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 附件名称
     *
     * Table:     attachment
     * Column:    filename
     * Nullable:  true
     */
    private String filename;

    /**
     * 附件别名
     *
     * Table:     attachment
     * Column:    filealias
     * Nullable:  true
     */
    private String filealias;

    /**
     * 附件类型
     *
     * Table:     attachment
     * Column:    type
     * Nullable:  true
     */
    private String type;

    /**
     * 附件的url地址
     *
     * Table:     attachment
     * Column:    fileurl
     * Nullable:  true
     */
    private String fileurl;

    /**
     * 附件路径
     *
     * Table:     attachment
     * Column:    filepath
     * Nullable:  true
     */
    private String filepath;

    /**
     * 附件大小
     *
     * Table:     attachment
     * Column:    filesize
     * Nullable:  true
     */
    private Double filesize;

    /**
     * 附件状态
     *
     * Table:     attachment
     * Column:    status
     * Nullable:  true
     */
    private Integer status;

    /**
     * 创建时间
     *
     * Table:     attachment
     * Column:    createtime
     * Nullable:  true
     */
    private Date createtime;

    /**
     * 更新时间
     *
     * Table:     attachment
     * Column:    updatetime
     * Nullable:  true
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attachment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}