package com.linzd.mobile.entity;

import java.io.Serializable;
import java.util.Date;

import io.swagger.annotations.ApiModel;
import lombok.Data;

/**
 * Table: organization
 */
@Data
@ApiModel(value="Organization",description="组织机构Organization")
public class Organization implements Serializable {
    /**
     * id
     *
     * Table:     organization
     * Column:    id
     * Nullable:  false
     */
    private Long id;

    /**
     * 名称
     *
     * Table:     organization
     * Column:    name
     * Nullable:  true
     */
    private String name;

    /**
     * 父级id
     *
     * Table:     organization
     * Column:    parentid
     * Nullable:  true
     */
    private Long parentid;

    /**
     * 机构代码
     *
     * Table:     organization
     * Column:    code
     * Nullable:  true
     */
    private String code;

    /**
     * 树级路径
     *
     * Table:     organization
     * Column:    isn
     * Nullable:  true
     */
    private String isn;

    /**
     * 状态
     *
     * Table:     organization
     * Column:    status
     * Nullable:  true
     */
    private String status;

    /**
     * 等级
     *
     * Table:     organization
     * Column:    rank
     * Nullable:  true
     */
    private String rank;

    /**
     * 描述
     *
     * Table:     organization
     * Column:    description
     * Nullable:  true
     */
    private String description;

    /**
     * 所属区域
     *
     * Table:     organization
     * Column:    areacode
     * Nullable:  true
     */
    private String areacode;

    /**
     * 排序
     *
     * Table:     organization
     * Column:    seq
     * Nullable:  true
     */
    private String seq;

    /**
     * 创建时间
     *
     * Table:     organization
     * Column:    createtime
     * Nullable:  true
     */
    private Date createtime;

    /**
     * 更新时间
     *
     * Table:     organization
     * Column:    updatetime
     * Nullable:  true
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organization
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}