package com.linzd.mobile.entity;

import io.swagger.annotations.ApiModel;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Table: user
 */
@Data
@ApiModel(value="User",description="用户对象user")
public class User implements Serializable {
    /**
     * 主键
     *
     * Table:     user
     * Column:    id
     * Nullable:  false
     */
    private Long id;

    /**
     * 登录名
     *
     * Table:     user
     * Column:    loginname
     * Nullable:  true
     */
    private String loginname;

    /**
     * 用户名
     *
     * Table:     user
     * Column:    name
     * Nullable:  false
     */
    private String name;

    /**
     * 密码
     *
     * Table:     user
     * Column:    password
     * Nullable:  false
     */
    private String password;

    /**
     * 组织机构id (和组织机构相关联)
     *
     * Table:     user
     * Column:    orgid
     * Nullable:  true
     */
    private Long orgid;

    /**
     * 岗位id
     *
     * Table:     user
     * Column:    jobid
     * Nullable:  true
     */
    private Long jobid;

    /**
     * 身份证号码
     *
     * Table:     user
     * Column:    idcard
     * Nullable:  true
     */
    private String idcard;

    /**
     * 地址
     *
     * Table:     user
     * Column:    address
     * Nullable:  true
     */
    private String address;

    /**
     * 手机号
     *
     * Table:     user
     * Column:    tel
     * Nullable:  true
     */
    private String tel;

    /**
     * 1男2 女
     *
     * Table:     user
     * Column:    sex
     * Nullable:  true
     */
    private Integer sex;

    /**
     * 邮箱地址
     *
     * Table:     user
     * Column:    email
     * Nullable:  true
     */
    private String email;

    /**
     * 备注
     *
     * Table:     user
     * Column:    remark
     * Nullable:  true
     */
    private String remark;

    /**
     * 排序
     *
     * Table:     user
     * Column:    seq
     * Nullable:  true
     */
    private String seq;

    /**
     * 令牌
     *
     * Table:     user
     * Column:    token
     * Nullable:  true
     */
    private String token;

    /**
     * 创建时间
     *
     * Table:     user
     * Column:    createtime
     * Nullable:  true
     */
    private Date createtime;

    /**
     * 更新时间
     *
     * Table:     user
     * Column:    updatetime
     * Nullable:  true
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}